var root = UnityEngine.GameObject.Find("玩家信息");
var p = root.GetComponent<NineGrid.Flow.PlayerInfoHudPresenter>();
var so = new UnityEditor.SerializedObject(p);
var sb = new System.Text.StringBuilder();
sb.Append("presenterOnRoot=").Append(p!=null);
sb.Append(" cur=").Append(so.FindProperty("currentHpText").objectReferenceValue!=null);
sb.Append(" slot=").Append(so.FindProperty("bloodSlot").objectReferenceValue!=null);
sb.Append(" col=").Append(so.FindProperty("bloodSlotCollider").objectReferenceValue!=null);
sb.Append(" goldTxt=").Append((so.FindProperty("goldText").objectReferenceValue as TMPro.TMP_Text)?.name);
sb.Append(" displayed=").Append(p!=null ? p.DisplayedGold.ToString() : "null");
var host = NineGrid.Flow.GoldHudDomainHost.Instance;
sb.Append(" goldHost=").Append(host!=null && host.IsAvailable);
return sb.ToString();
